### ISSUE TITLE
Sliders get stuck in text-input mode

### ISSUE THREAD

**Issue by sansumbrella** [simongeilfus/Cinder-ImGui#7] opened 2015-07-17 19:38 UTC
What causes sliders (`ui::SliderFloat`) to switch over to text-input mode? Sometimes the gui switches modes and I can no longer slide the sliders until I restart the application (attempting to slide creates a text input buffer). Any idea what might be causing this?

May be a how-to-use question more than a bug, but it's unclear what causes the switch.

**Comment by simongeilfus** [comment] 2015-07-18 11:39
Hey David,
Ctrl or Cmd-Click does that and changing focus to the slider as well (by using the tab key for example). I'm still having [an issue](https://github.com/cinder/Cinder/issues/1010) with modifier keys and not quite sure my code handling this is correct, so I don't know, might be a bug.

Could you share some steps to re-produce that here?

**Comment by simongeilfus** [comment] 2015-07-18 11:43
Re-reading your message, I guess it's probably related to what I explain in the issue I linked above. You might need to have a look at the keyDown/keyUp functions to see what's going on. If a modifier key doesn't get released, it will probably mess up with your interactions with the UI.

Btw I've not tested this code on windows for a while.

**Comment by sansumbrella** [comment] 2015-07-18 15:21
The command-key makes sense as a reason. I often `cmd+tab` between applications, so it is probably getting switched then. I'll check on monday whether hitting `cmd` in-app resets the behavior.

**Comment by simongeilfus** [comment] 2015-07-20 14:42
Yes, sometimes ```cmd+tab``` followed by a click on the app doesn't give back the focus to the UI. I also tried to aggressively switch apps while pressing modifier keys and clicking on a slider, and I do get stuck into text mode as well. (Pressing ```cmd``` does reset the intended behavior)

A temporary solution might be to use ```ctrl``` instead of ```cmd``` on osx, I'll try to do that in a next update.

**Comment by sansumbrella** [comment] 2015-07-20 22:13
Hitting command when I'm back in the app restores slide-ability. So it's a bit of a weird issue, but workable.

**Comment by CRasterImage** [comment] 2015-12-04 23:44
This is a problem in Windows as well.  Alt + Tab, the case of Windows.

I think the problem is that keyboard input focus is changing from your Cinder app to something else.  So Cinder apps don't receive a keyUp for Cmd or Alt or any key that was held down when input focus was taken away.  So they think the key is still down when focus comes back to your Cinder app.

Part of the problem is that ImGui is trying to remember the state of every key.  It has an array of states for 500+ keys.  I am not sure what the array is being used for.   If it is mainly to know whether Shift, Cmd, Ctrl, Alt, etc.. key is down, that information is availble in the Event info for mouse and key actions.  I think that data is correct.  While the array has out-of-date information.  So maybe the array isn't needed?

Another way to fix it is:  Convince the Cinder guys to add a couple new emit-able events.  takingFocus() and losingFocus().  Then the Cinder-ImGui could listen for those events and wipe the key state array clean on either or both of those notifications.

This kind of seems like an important issue.   How can an application ask it's users to not Cmd + Tab or Alt + Tab to other applications?

**Comment by CRasterImage** [comment] 2015-12-05 01:13
Actually, I take some of that back.  It seems that there are signals for this getSignalDidBecomeActive() and getSignalWillResignActive().

I tried setting all 512 io.KeyDown[] items to false, in a handler for that signal and the problem didn't go away.   Still researching how ImGui handles events.  Kind of confusing.

**Comment by CRasterImage** [comment] 2015-12-05 01:50
Ok, I seem to have fixed it, for me.  Let me know if this fixes the problem for Mac "Cmd" key issues.

Add
```javascript
#include "imgui_internal.h"
```
for access to the IM_ARRAYSIZE() macro.

Then, in your App's setup() member function, add these:

```javascript
   getSignalDidBecomeActive().connect([this](){
      for(int i = 0; i < IM_ARRAYSIZE(ImGui::GetIO().KeysDown)/*512*/; i++){
         ImGui::GetIO().KeysDown[i] = false;
         ImGui::GetIO().KeysDownDuration[i] = 0.0f;
         ImGui::GetIO().KeysDownDurationPrev[i] = 0.0f;
      }
      ImGui::GetIO().KeyCtrl = false;
      ImGui::GetIO().KeyShift = false;
      ImGui::GetIO().KeyAlt = false;
   });

   getSignalWillResignActive().connect([this](){
      for(int i = 0; i < IM_ARRAYSIZE(ImGui::GetIO().KeysDown)/*512*/; i++){
         ImGui::GetIO().KeysDown[i] = false;
         ImGui::GetIO().KeysDownDuration[i] = 0.0f;
         ImGui::GetIO().KeysDownDurationPrev[i] = 0.0f;
      }
      ImGui::GetIO().KeyCtrl = false;
      ImGui::GetIO().KeyShift = false;
      ImGui::GetIO().KeyAlt = false;
   });
```

**Comment by simongeilfus** [comment] 2016-01-04 09:43
Thanks a lot for this Shawn!
It doesn't fix all key related issues, but it's perfect until we have better key support in Cinder! I implemented your fix in this [commit](https://github.com/simongeilfus/Cinder-ImGui/commit/0f11852929506c274de0ef00fd39acab548f725f).

I'll close this for now, let me know if you're still seeing anything weird.

**Closed by simongeilfus** 2016-01-04 09:43 UTC
